name: test-elastic
#recipe: custom
services:
  monitoring:
    type: php:8.0
    via: apache
    version: 2.4
    webroot: www # document root
    ssl: true
    xdebug: true
    config:
      php: lando/php/php.ini
      #server: lando/http/httpd.conf
      #vhosts: config/vhost/default-ssl.conf
proxy:
  monitoring:
    - test-elastic.swsystems.cz

# pripojeni z kontejneru na local DB
# docker.for.mac.localhost:3306   docker.for.mac.host.internal:3306

  #engineConfig:
#  host: 127.0.0.1
#  port: 4333
#  socketPath: null



#bindAddress: "0.0.0.0"

  #  pma:
  #    type: phpmyadmin
  #    proxy:
  #      appserver:
  #        - it22020.ssemi.cz

#  database1: # database1:3306 je spojeni na db
#    type: mysql:8.0
#    portforward:  3306
#    creds:
#      user: user1  # root je bez hesla
#      password: test
#      database: database1
#      config:
#      database: config/mysql/my_custom.cnf

