FROM php:8.0-apache AS nette_elastic80

RUN a2enmod rewrite

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y \
        cron \
        libpng-dev \
        zlib1g-dev \
        libpng-dev \
        mc \
        lynx \
        libjpeg-dev \
        libfreetype6-dev \
        iproute2 \
        git \
        zip \
        unzip \
        iputils-ping \
        net-tools \
        telnet \
    && apt-get clean

    COPY ./docker/elasticsearch.yml /usr/share/elasticsearch/config



#RUN groupadd -g 1000 elasticsearch && useradd -u 1000 -g 1000 -G 0 -m -d /usr/share/elasticsearch elasticsearch \
#		&& chmod 0775 /usr/share/elasticsearch && chgrp 0 /usr/share/elasticsearch

# install APT transport and wget
#RUN apt-get update && \
#  apt-get install -y --no-install-recommends \
#  apt-transport-https \
#  wget -y
#
#RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-arm64.deb

RUN docker-php-ext-install mysqli

COPY ./docker/php.ini /etc/php/php.ini
COPY ./docker/add-host-domain.sh /add-host-domain.sh
COPY ./docker/run.sh /run.sh

RUN chmod +x /add-host-domain.sh
RUN chmod +x /run.sh
# Create the log file to be able to run tail
RUN touch /var/log/container.log

RUN docker-php-ext-configure gd && docker-php-ext-install gd
RUN docker-php-ext-enable gd

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-enable pdo_mysql

RUN pecl install mailparse
RUN docker-php-ext-enable mailparse

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN rm -rf /etc/apache2/sites-enabled/*
RUN rm -rf /etc/apache2/sites-available/*
RUN echo "" > /etc/apache2/ports.conf
RUN printf '\n\nServerName control.local\n\n' >> /etc/apache2/apache2.conf
RUN rm -rf /var/www/html

ENTRYPOINT bash /run.sh